name: "Check code formatting"

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "main"

jobs:
  check-formatting:
    # List of available images:
    # https://github.com/actions/runner-images?tab=readme-ov-file#available-images
    runs-on: "ubuntu-24.04"
    steps:
      - name: "Checkout repository."
        # https://github.com/actions/checkout
        uses: "actions/checkout@v6"

      - name: "Install Node.js."
        # https://github.com/actions/setup-node
        uses: "actions/setup-node@v6"
        with:
          node-version: "^24.11.1"
          cache: "npm"

      - name: "Install dependencies."
        run: "npm ci"

      - name: "Check formatting."
        run: "npm run check-formatting"
